services:

  cassandra-1:
    image: cassandra:latest
    container_name: "cassandra-1"
    ports:
      - 7000:7000
      - 9042:9042
    networks:
      - cassandra-net
    environment:
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=auto  # default, use IP addr of container # = CASSANDRA_BROADCAST_ADDRESS
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=my-datacenter-1
      - CASSANDRA_SEEDS=cassandra-1
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=512M
    volumes:
      - cassandra-node-1:/var/lib/cassandra:rw
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces' || exit 1"]
      interval: 30s
      start_period: 2m
      timeout: 10s
      retries: 5

  cassandra-2:
    image: cassandra:latest
    container_name: "cassandra-2"
    ports:
      - 9043:9042
    networks:
      - cassandra-net
    environment:
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=auto  # default, use IP addr of container # = CASSANDRA_BROADCAST_ADDRESS
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=my-datacenter-1
      - CASSANDRA_SEEDS=cassandra-1
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=512M
    depends_on:
      cassandra-1:
        condition: service_healthy
    volumes:
      - cassandra-node-2:/var/lib/cassandra:rw
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces' || exit 1"]
      interval: 30s
      start_period: 2m
      timeout: 10s
      retries: 5

  cassandra-3:
    image: cassandra:latest
    container_name: "cassandra-3"
    ports:
      - 9044:9042
    networks:
      - cassandra-net
    environment:
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=auto  # default, use IP addr of container # = CASSANDRA_BROADCAST_ADDRESS
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=my-datacenter-1
      - CASSANDRA_SEEDS=cassandra-1
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=512M
    depends_on:
      cassandra-2:
        condition: service_healthy
    volumes:
      - cassandra-node-3:/var/lib/cassandra:rw
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces' || exit 1"]
      interval: 30s
      start_period: 2m
      timeout: 10s
      retries: 5

  cassandra-setup:
    image: cassandra:latest
    container_name: "cassandra-setup"
    ports:
      - 9045:9042
    networks:
      - cassandra-net
    environment:
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=auto  # default, use IP addr of container # = CASSANDRA_BROADCAST_ADDRESS
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=my-datacenter-1
      - CASSANDRA_SEEDS=cassandra-1
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=512M
    depends_on:
      cassandra-3:
        condition: service_healthy
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        until cqlsh cassandra-1 9042 -e "DESCRIBE KEYSPACES" 2>/dev/null; do
        echo "Cassandra jeszcze niegotowa, czekam..."
        sleep 10
        done
        cqlsh cassandra-1 9042 -e "CREATE KEYSPACE IF NOT EXISTS urlshortener WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 3};"
        echo "Keyspace urlshortener gotowy."


  read-service:
    build: ./readService/
    develop:
      watch:
        - action: rebuild
          path: ./readService/src
        - action: rebuild
          path: ./readService/pom.xml
    ports:
      - 8082:8082
    networks:
      - cassandra-net
    depends_on:
      cassandra-setup:
        condition: service_completed_successfully
    environment:
      - CASSANDRA_CONTACT_POINTS=cassandra-1
      - CASSANDRA_PORT=9042
      - CASSANDRA_DATACENTER=my-datacenter-1
      - CASSANDRA_KEYSPACE=urlshortener

  write-service:
    build: ./writeService/
    ports:
      - 8081:8081
    networks:
      - cassandra-net
    depends_on:
      cassandra-setup:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - CASSANDRA_CONTACT_POINTS=cassandra-1
      - CASSANDRA_PORT=9042
      - CASSANDRA_DATACENTER=my-datacenter-1
      - CASSANDRA_KEYSPACE=urlshortener


  cleanup-service:
    build: ./cleanupService
    environment:
      CASSANDRA_CONTACT_POINTS: cassandra-1
      CASSANDRA_PORT: 9042
      CASSANDRA_DATACENTER: my-datacenter-1
      CASSANDRA_KEYSPACE: urlshortener
    depends_on:
      cassandra-setup:
        condition: service_completed_successfully
    networks:
      - cassandra-net

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - cassandra-net
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  moderation-service:
    build: ./moderationService/
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - cassandra-net

networks:
  cassandra-net:

volumes:
  cassandra-node-1:
  cassandra-node-2:
  cassandra-node-3: